name: volgrids
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - attr=2.5.2=h39aace5_0
  - blosc=1.21.6=hef167b5_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cftime=1.6.5=py314hc02f841_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py314h9891dd4_3
  - cpython=3.14.2=py314hd8ed1ab_100
  - cycler=0.12.1=pyhcf101f3_2
  - filelock=3.20.3=pyhd8ed1ab_0
  - fonttools=4.61.1=pyh7db6752_0
  - freetype=2.14.1=ha770c72_0
  - griddataformats=1.0.2=pyhd8ed1ab_1
  - gsd=4.2.0=h31e983c_0
  - h5py=3.15.1=nompi_py314hc32fe06_101
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h1b119a7_104
  - icu=78.2=h33c6efd_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py314h97ea11e_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=h5eee18b_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h9d88235_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.8=py314h1194b4b_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdanalysis=2.10.0=py314ha0b5721_1
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mrcfile=1.5.4=pyhd8ed1ab_0
  - msgpack-python=1.1.2=py314h9891dd4_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - netcdf4=1.7.4=nompi_py314h4ae7121_101
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.1=py314h2b28147_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha0b5721_2
  - patsy=1.0.2=pyhcf101f3_0
  - pillow=12.1.0=py314h8ec4b1a_0
  - pip=25.3=pyh0d26453_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pyparsing=3.3.1=pyhcf101f3_0
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.2=h4df99d1_100
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=2_cp314
  - pytng=0.3.4=py314hddf221e_0
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.3=hc2a1206_0
  - scikit-learn=1.8.0=np2py314hf09ca88_1
  - scipy=1.17.0=py314hf07bd8e_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.1=he0a8d7e_0
  - statsmodels=0.14.6=py314hc02f841_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py314h5bd0f2a_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=h11fc155_0
